### ISSUE TITLE
初音ミク

### ISSUE THREAD

**Issue by arch-herobrine** [Gakuto1112/FiguraBlueArchiveCharacters#78]
## 概要
「初音ミク」を作成する。

<details>
  <summary>キャラクターイラスト</summary>

  ![初音ミク](https://pbs.twimg.com/media/FC_9Q7WaAAAYJEG.jpg:large)

  
</details>

## 備考
コラボ生徒

## タスク
- [ ] このキャラクターの作成状況を「作成中」に移動する。
- [ ] 参考リソース集め
- [ ] 基本情報を設定（名前・誕生日など）
- [ ] デフォルト衣装のモデルを作成
- [ ] デフォルト衣装の揺れ物を設定
- [ ] 固有武器のモデルを作成
- [ ] 固有武器の挙動（位置・向き・射撃音など）を設定
- [ ] デフォルト衣装でのExスキルアニメーションを作成
   - [ ] アニメーション中に使用するモデルを作成
   - [ ] BBアニメーションを作成
   - [ ] カメラワークを作成
   - [ ] パーティクルなどの視覚的演出を作成
   - [ ] 効果音を追加
- [ ] デフォルト衣装での防具との見た目の整合性を確認
- [ ] デフォルト衣装での死亡アニメーションとの見た目の整合性を確認
- [ ] デフォルト衣装でのサムネイル用の画像を作成（キャラクターイラストを作ったモデルで再現する）

- [ ] 設置物を使わない場合はサンプル設置物の削除
- [ ] このキャラクターの作成状況を「作成済み」に移動する。

以下は個人（[Gakuto1112](https://github.com/Gakuto1112)）的なタスク

- [ ] （通常衣装でのメモリアルロビーを再現）

**Comment by Gakuto1112** [comment]
提案ありがとうございます。

確かに、初音ミクは、コラボキャラクターとして実装はされていますが、ブルーアーカイブのオリジナルキャラクターではないため、作成は致しません。

なお、過去に初音ミクのアバターを作成しましたので、そちらも是非ご覧下さい。
https://github.com/Gakuto1112/StrawberryMiku
