### ISSUE TITLE
[1.21.1]Izuna Kuda's EX skill animation fails to play

### ISSUE THREAD

**Issue by OvOla2** [Gakuto1112/FiguraBlueArchiveCharacters#84]
https://github.com/FiguraMC/Figura/issues/271

**Comment by Gakuto1112** [comment]
@OvOla2 
Thank you for using my avatars and reporting issues!
The issue that you report has been confirmed. I will deal with this issue until releasing the next release.

**Comment by Gakuto1112** [comment]
## 原因
> That shader was removed in **24w11a** (1.20.5), according to [misode/mcmeta](https://github.com/misode/mcmeta):
> 
> [diff of assets](https://github.com/misode/mcmeta/commit/9d3ee4cced7b202cb748340db76cf63745cb6c8a#diff-b7fd1849b49fe57bf02da318ba35518d87fbcfbba3155661ab264f359337f665)

利用していたポストレンダーエフェクトがゲームから削除された模様。
無いものを参照しようとしているので、当然エラーが出る。

## 解決方法
`compatibility_util.lua`で`renderer:setPostEffect()`をラップする。
- ゲームバージョンが1.20.5以上 → 何もさせない
- ゲームバージョンが1.20.4以下 → `renderer:setPostEffect()`を実行させる。

## 影響を受けるキャラクター
- イズナ（通常・水着）
- シロコ（水着）
- ホシノ（臨戦 - 防御型・臨戦 - 攻撃型）

## タスク
- [x] `compatibility_utils.lua`に`renderer:setPostEffect()`をラッパー関数を実装
- [x] 既存キャラクターのPostEffectをラップ
  - [x] イズナ（通常） 
  - [x] イズナ（水着）
  - [x] シロコ（水着）
  - [x] ホシノ（臨戦 - 防御型）
  - [x] ホシノ（臨戦 - 攻撃型）

**Comment by Gakuto1112** [comment]
@OvOla2 
This issue has been fixed in v2.0.0.
https://github.com/Gakuto1112/FiguraBlueArchiveCharacters/releases/tag/v2.0.0

Thanks for your report!
