### ISSUE TITLE
[1.21.1]The camera viewport can be controlled by the mouse when playing EX skill animations.

### ISSUE THREAD

**Issue by OvOla2** [Gakuto1112/FiguraBlueArchiveCharacters#92]
*This issue affects all avatars

Figura version: Both are 0.1.5rc4-neoforge
Avatars version: Both are 2.0.0
No other mods/plugins are installed.

In version 1.20.4:Everything is working normally(the viewport does not move with the mouse.)
![1733552158909](https://github.com/user-attachments/assets/52d10873-92b4-400a-9ac3-dd76271e5d07)

In version 1.21.1:The viewport moves with the mouse
![1733551742128](https://github.com/user-attachments/assets/7be02db3-7bc6-44a0-9b0b-a2a1b3882692)

• This phenomenon also exists in the earlier version 1.9.6.

**Comment by OvOla2** [comment]
For some reason, GitHub didn't successfully display the GIF.😐

**Comment by Gakuto1112** [comment]
@OvOla2 
Thank you for using my avatars and reporting issues!

This issue causes by Figura v0.1.5-rc.4. This means that I cannot deal with this issue.
https://discord.com/channels/1129805506354085959/1308937694297980948/1314868036314075236

As evidence, you can try running the following command:
```
/figura run renderer:setCameraRot(0, 0, 0)
```
This command usually fixes the camera rotation, but it doesn't do that in Figura versions that you are using.

Please use Forge or Fabric versions of Figura, or Minecraft 1.20.6 or older if you can.

**Comment by Gakuto1112** [comment]
@OvOla2 
This issue was fixed in Figura 0.1.5-rc.6.

> Custom Camera rotation was broken on NeoForge 1.21

Refered from: https://discord.com/channels/1129805506354085959/1141418789423030342/1318441781951594537
