### ISSUE TITLE
The mouth area has texture missing when Momoi uses the sweating emoji.

### ISSUE THREAD

**Issue by OvOla2** [Gakuto1112/FiguraBlueArchiveCharacters#93]
Momoi:
![2024-12-09_22 10 09](https://github.com/user-attachments/assets/08aaa6ca-3d1e-4b72-9374-bb27ac543442)
Midori:
![2024-12-09_22 23 24](https://github.com/user-attachments/assets/b90844a8-eeeb-416b-9d3b-2b8a82069f84)

**Comment by Gakuto1112** [comment]
@OvOla2
Thank you for using my avatars and reporting issues!

Please look your picture carefully.
You can see Momoi's teeth at her mouth.
![image](https://github.com/user-attachments/assets/a6945097-2dde-4800-801d-10cc60ec42a6)

If you want to tell me something related to this issue, please feel free like to post a your message!

**Comment by OvOla2** [comment]
> 感谢您使用我的头像并报告问题！
> 
> 请仔细查看您的照片。你可以看到桃井的牙齿在她的嘴上。 ![image](https://private-user-images.githubusercontent.com/90630001/394795118-a6945097-2dde-4800-801d-10cc60ec42a6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM5MzAxODgsIm5iZiI6MTczMzkyOTg4OCwicGF0aCI6Ii85MDYzMDAwMS8zOTQ3OTUxMTgtYTY5NDUwOTctMmRkZS00ODAwLTgwMWQtMTBjYzYwZWM0MmE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjExVDE1MTEyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcyYTkwMmMzMTEyNGQ5MGJiMjMxOTQ4M2FlMmVhNDM4M2I1MzU5YTVhZTQ2YmFhNjEzY2NlYzcyOGI4NGQ4NTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.6XhXfUmEi5Y6T2vHVEY6Zow8X04e1xYRUi17t2WRraU)
> 
> 如果您想告诉我与此问题相关的事情，请随时发布您的信息！

Oh, sorry,but I think it looks a bit strange🤔
